#!/usr/bin/env python
# -*- coding: utf-8 -*-

import yaml
from lib import update_checker as uc
from lib import slack_bot as sb

if __name__ == "__main__":

    f = open("config.yml", 'r')
    data = yaml.load(f)
    f.close
    checker = uc.UpdateChecker("http://www.keyakizaka46.com")
    entries = checker.latest_entries()
    updated = checker.updated_entries(entries)
    bot = sb.SlackBot(data['token'])

    for entry in updated:
        bot.post_message(entry)
        if entry["imgs"] != "":
            bot.post_imgs(entry)
